collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3571064139250666
  brandStrength: 0.740748749114573
  rhythmicContrast: 0.703800946706906
  brandColors:
    - '#E7E8D1'
    - '#D3CEAA'
    - '#FBF7E4'
    - '#424242'
    - '#8E001C'
  lightness: 0.5991349520627409
typography_spectrum: 0.8715651
layout_spectrum: 0
name: Sacred Instrument Number One
